### ISSUE TITLE
V2.0 Features

### ISSUE THREAD

**Issue by grantcm** [CS2103AUG2017-T12-B4/main#10]
Issue tracker for new features

**Comment by grantcm** [comment]
Dropdown bar for using UI to execute commands

**Comment by aali195** [comment]
I think we can get the dropdown bar done as well as complete GUI support before v1.5 if things go as they are.

**Comment by aali195** [comment]
Enhancement to the image command:
- Delete the image file after an image/person is removed.

**Comment by LauY99** [comment]
Autodelete feature to clear expired persons every time TouristBook is starting up
