### ISSUE TITLE
Refocus of Developer Guide

### ISSUE THREAD

**Issue by LauY99** [CS2103AUG2017-T12-B4/main#5]
Since we have decided to target the address book toward tour guides, we need to modify the Developer Guide to focus more on how a tour guide would use our address book.

**Comment by LauY99** [comment]
I've read through the existing user stories, here are the ones that (I think) target tour guides:
Line 711: put persons into groups
Line 733: set expiry date to a person
Line 739: add multiple persons by importing CSV file
If we are to specialize our address book for tour guides, we might need to up the priorities of these user stories. (Currently, none of them are 3-star)

**Comment by aali195** [comment]
We can also add a scenario to the developer guide explaining the the situation, the new target audience as well as a quick description of what the final product will contain. 

We should separate those features into potential milestones for the final product as well. So for example, have the grouping feature be something to be done by version 1.5.

**Comment by aali195** [comment]
We can then start working on a few designs for the end product.

**Comment by grantcm** [comment]
I think we need to have several more user cases for the end product. We could also include user cases that will improve other parts of the program, not limited to the tour guide functionality, such as making entering commands faster or other ui improvements.

**Comment by LauY99** [comment]
Since one of our features is grouping, should we add more functionalities related to that? Like search and sort by groups. I'm also thinking a group filter on top of the current search function.

**Comment by aali195** [comment]
Refocusing should be done. Review my PR to see if I have missed anything and let me know.

**Comment by aali195** [comment]
Please update the developer and user guides as you implement features. You will most likely be better at explaining them than me.

**Comment by aali195** [comment]
Refocusing is done. Closing it.
